
-- PIZZA DE SILVA – SUPABASE SCHEMA
create extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  status text not null default 'new',
  eta integer,
  expires_at timestamptz,
  total numeric(10,2) not null,
  customer jsonb not null,
  items jsonb not null,
  cancel_reason text
);

create table if not exists public.store_settings (
  id integer primary key default 1 check (id = 1),
  store_open boolean not null default true,
  "storeOpen" boolean,
  "openingHoursText" text,
  "deliveryAreaText" text,
  "deliveryMinimum" numeric(10,2) not null default 0,
  "deliveryFee" numeric(10,2) not null default 0,
  "autoCancelMinutes" integer not null default 5
);

insert into public.store_settings (id,"storeOpen","openingHoursText","deliveryAreaText","deliveryMinimum","deliveryFee","autoCancelMinutes")
values (1,true,'Öffnungszeiten bitte eintragen','Liefergebiet bitte eintragen',0,0,5)
on conflict (id) do nothing;

alter table public.orders enable row level security;
alter table public.store_settings enable row level security;

-- Kunden dürfen neue Bestellungen anlegen.
drop policy if exists "customer insert orders" on public.orders;
create policy "customer insert orders" on public.orders
for insert to anon with check (status = 'new');

-- Kundenstatus kann anhand der Bestell-ID gelesen werden.
-- In einer final gehärteten Version sollte zusätzlich ein zufälliges Status-Token verwendet werden.
drop policy if exists "customer read own order by id" on public.orders;
create policy "customer read own order by id" on public.orders
for select to anon using (true);

-- Öffentliche Shop-Einstellungen dürfen gelesen werden.
drop policy if exists "public read store settings" on public.store_settings;
create policy "public read store settings" on public.store_settings
for select to anon using (true);

-- WICHTIG:
-- Admin-UPDATE/SELECT-Rechte sollten über Supabase Auth für den Admin ergänzt werden,
-- bevor die Seite öffentlich live geht. Der Vorschau-Login "desilva" ist NICHT für Livebetrieb gedacht.
